jenkins:
  numExecutors: 1
  quietPeriod: 0

  # Default LDAP configuration
  securityRealm:
    ldap:
      configurations:
        - server: ldaps://ldap.corp.redhat.com
          rootDN: dc=redhat,dc=com
          userSearch: uid={0}
          groupSearchBase: ou=groups
          groupSearchFilter: (& (cn={0}) (objectclass=posixGroup))
          groupMembershipStrategy:
            fromGroupSearch:
              filter: memberUid={1}
      cache:
        size: 100
        ttl: 10
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseInsensitive

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "ci-support" # Access for the support team
              - "sysops" # Access for the support team
              - "ops-qe-jenkins-ci-automation" # TODO document
              - "ccit-test" # OpenShift automation account
              - "cci-octopus" # Instance telemetry collection

security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: false

unclassified:
  shell:
    shell: "bash"

jobs:
  - url: "${CASC_SEED_JOB_URL:-https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-jenkins/jcasc/raw/master/job-configurator.jobdsl.groovy}"
  - script: "queue('job-configurator')"

