jenkins:
  # Number of executors on Master node
  numExecutors: 1
  # Do not let builds waiting in Jenkins queue before they are assigned to agents
  quietPeriod: 0
  # Port JNLP agents are connecting to
  slaveAgentPort: 50000

  # Default corporate LDAP configuration
  securityRealm:
    ldap:
      configurations:
        - server: ldaps://ldap.corp.redhat.com
          rootDN: dc=redhat,dc=com
          userSearch: uid={0}
          groupSearchBase: ou=groups
          groupSearchFilter: (& (cn={0}) (objectclass=posixGroup))
          groupMembershipStrategy:
            fromGroupSearch:
              filter: memberUid={1}
      cache:
        size: 100
        ttl: 10
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseInsensitive

  authorizationStrategy: "loggedInUsersCanDoAnything"

unclassified:
  extendedEmailPublisher:
    defaultSuffix: "@redhat.com"
    smtpServer: "smtp.corp.redhat.com"

security:
  globalJobDslSecurityConfiguration:
    # Permit Job DSL to be run without the hassle of script security
    useScriptSecurity: false

jobs:
  # Create and invoke the managed seed-job
  - url: "${CASC_SEED_JOB_URL:-https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-jenkins/jcasc/raw/master/job-configurator.jobdsl.groovy}"
  - script: "queue('job-configurator')"
