jenkins:
  # Number of executors on Master node
  numExecutors: 1
  # Do not let builds waiting in Jenkins queue before they are assigned to agents
  quietPeriod: 0
  # Port JNLP agents are connecting to
  slaveAgentPort: 50000

  # Default corporate LDAP configuration
  securityRealm:
    ldap:
      cache:
        size: 100
        ttl: 10
      configurations:
        - server: ldaps://ldap.corp.redhat.com
          rootDN: dc=redhat,dc=com
          inhibitInferRootDN: false
          userSearch: uid={0}
          groupSearchFilter: (& (cn={0}) (objectclass=GroupOfUniqueNames))
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseInsensitive

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "cci-octopus" # Instance telemetry collection
              - "ci-support" # Access for the support team
              - "sysops" # Access for the support team
              - "ops-qe-jenkins-ci-automation" # TODO document
              - "ccit-test" # OpenShift automation account
          - name: "admin_read"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
          - name: "anonymous"
            description: "Anonymous users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/ExtendedRead"
              - "View/Read"
            assignments:
              - "anonymous"

  globalNodeProperties:
    - envVars:
        env:
          - key: JOB_CONFIGURATOR_MAIL_RECIPIENTS
            value: "" # List of space separated addresses to be mailed when job-configurator fails
          - key: JOB_CONFIGURATOR_LABEL
            value: "" # Label where job-configurator should be run

  updateCenter:
    sites:
    - id: "default"
      url: "http://do.not.install.plugins.manually.use.plugins.txt"

unclassified:
  mailer:
    charset: "UTF-8"
    smtpHost: "smtp.corp.redhat.com"
    useSsl: false

security:
  globalJobDslSecurityConfiguration:
    # CCI-JD-REQUIREMENT: Permit Job DSL to be run without the hassle of script security
    useScriptSecurity: false
  kerberosSso:
    enabled: true
    krb5Location: '/etc/krb5.conf'
    loginLocation: '/etc/login.conf'
    loginServerModule: 'spnego-server'
    loginClientModule: 'spnego-client'
    anonymousAccess: true
    allowLocalhost: false
    allowBasic: true
    allowDelegation: false
    # While strictly speaking insecure, this is a) required for localhost access
    # and b) harmless in production that does not support http at all
    allowUnsecureBasic: true
    promptNtlm: false

jobs:
  # CCI-JD-REQUIREMENT: Create the managed seed-job
  - url: "${CASC_SEED_JOB_URL:-https://gitlab.cee.redhat.com/ccit/jenkins-csb/raw/2-190-3/cci-jd/job-configurator.jobdsl.groovy}"
  # CCI-JD-REQUIREMENT: and invoke it
  - script: "queue('job-configurator')"
