jenkins:
  numExecutors: 1
  quietPeriod: 0
  slaveAgentPort: -1

  # Default LDAP configuration
  securityRealm:
    ldap:
      configurations:
        - server: ldaps://ldap.corp.redhat.com
          rootDN: dc=redhat,dc=com
          userSearch: uid={0}
          groupSearchBase: ou=groups
          groupSearchFilter: (& (cn={0}) (objectclass=posixGroup))
          groupMembershipStrategy:
            fromGroupSearch:
              filter: memberUid={1}
      cache:
        size: 100
        ttl: 10
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseInsensitive

  authorizationStrategy: "loggedInUsersCanDoAnything"


security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: false

unclassified:
  location:
    url: "${CASC_SELF_URL:-http://localhost:8080/}"

  shell:
    shell: "bash"

jobs:
  - url: "${CASC_SEED_JOB_URL:-https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-jenkins/jcasc/raw/master/job-configurator.jobdsl.groovy}"
  - script: "queue('job-configurator')"

