static defaultSetting(def job) {
    job.with {
        logRotator {
            numToKeep(10)
        }
    }
}

static defaultSettingPipeline(def job) {
    job.with {
        logRotator {
            numToKeep(10)
        }
    }
}

static pipelineDefault(def job, def scriptText) {
    job.with {
        description("Autogenerated job from Jenkinsfile")
        defaultSettingPipeline(job)
        definition {
            cps {
                script(scriptText)
                sandbox()
            }
        }
    }
}

